name: Deploy to nguyen.me.uk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploying
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ngy.ecam.be
          username: khoi
          port: 8022
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: /home/khoi/git/www/dist
          rm: true
      - name: Restarting the server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ngy.ecam.be
          username: khoi
          port: 8022
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/khoi/git/www
            git pull
            pm2 restart www
