name: Deploy to nguyen.me.uk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Copy repository contents
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ngy.ecam.be
          username: khoi
          port: 8022
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/khoi/git/www"
      - name: Building
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ngy.ecam.be
          username: khoi
          port: 8022
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/khoi/git/www
            npm install
            git config --unset core.hooksPath
            npm run build --update-env
            pm2 restart www
