name: Deploy to nguyen.me.uk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Building
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ngy.ecam.be
          username: khoi
          port: 8022
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/khoi/git/www
            git pull
            npm install
            git config --unset core.hooksPath
            npm run build --update-env
            pm2 restart www
